org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_id=sulfurcavesplus
mod_name=Sulfur Caves Plus
mod_version=1.1.7-26.2-neoforge
mod_group=net.crossface22.sulfurcavesplus
mod_authors=CrossFace22
mod_description=A mod that adds new content to the Sulfur Caves biome: Sulfur Spiders, Corrosion and more.
license=CC0-1.0

minecraft_version=26.2
java_version=25
neoforge_version=26.2.0.0-beta
moddevgradle_version=2.0.141
